"""
Verifies every generated artifact is in sync with its canonical *-openapi.json source.

For each `<api>/<api>-openapi.json` the repo also commits these generated files:
  - `<api>/<api>-openapi.yaml`  (regenerated by scripts/sync_yaml.py)
  - `<api>/<api>-mcp.json`       (regenerated by scripts/make_mcp.py, seven APIs only)
  - `<api>/<api>-ptc.json`       (regenerated by scripts/make_ptc.py, seven APIs only)

Both agent surfaces exclude the same three APIs (see make_mcp.EXCLUDED). For those the check
makes sure neither a -mcp.json nor a -ptc.json exists, because a stray file there would put
an excluded operation back in reach of an agent.

All are hand-checked-in but machine-produced, so they can silently drift when a JSON spec
is edited without re-running the generators. This check regenerates each in memory and compares
against the committed file, failing (exit 1) with the exact regen command for any mismatch.
Nothing is written to disk.

Usage: uv run python scripts/check_generated.py [spec.json ...]   (default: all */*-openapi.json)
"""

import pathlib
import sys

from make_mcp import EXCLUDED, render_mcp
from make_ptc import render_ptc
from sync_yaml import render_yaml
import json


def check(json_path: pathlib.Path) -> tuple[list[str], list[str]]:
    """Returns (violations, artifacts checked) — the second is printed on success so a
    reader can see that MCP and PTC were covered, or skipped for an excluded API."""
    spec = json.loads(json_path.read_text(encoding="utf-8"))
    api = json_path.parent.name
    excluded = api in EXCLUDED
    violations, checked = [], ["yaml"]

    yaml_path = json_path.with_suffix(".yaml")
    expected_yaml = render_yaml(spec)
    if not yaml_path.exists() or yaml_path.read_text(encoding="utf-8") != expected_yaml:
        violations.append(
            f"{yaml_path} is stale — run: uv run python scripts/sync_yaml.py {json_path}"
        )

    for kind, render, script in (("mcp", render_mcp, "make_mcp.py"), ("ptc", render_ptc, "make_ptc.py")):
        path = pathlib.Path(str(json_path).replace("-openapi.json", f"-{kind}.json"))
        if excluded:
            checked.append(f"{kind} excluded")
            if path.exists():
                violations.append(
                    f"{path} must not exist — {api} is excluded from the {kind.upper()} surface"
                )
            continue
        checked.append(kind)
        expected = render(spec)
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            violations.append(
                f"{path} is stale — run: uv run python scripts/{script} {json_path}"
            )

    return violations, checked


def main() -> int:
    if len(sys.argv) > 1:
        spec_files = [pathlib.Path(a) for a in sys.argv[1:]]
    else:
        spec_files = sorted(pathlib.Path(".").glob("*/*-openapi.json"))

    if not spec_files:
        print("No spec files found.")
        return 1

    all_ok = True
    for path in spec_files:
        violations, checked = check(path)
        if violations:
            all_ok = False
            for v in violations:
                print(f"[FAIL] {v}")
        else:
            print(f"[OK] {path.parent.name} ({', '.join(checked)})")

    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
