"""
Verifies every generated artifact is in sync with its canonical *-openapi.json source.

For each `<api>/<api>-openapi.json` the repo also commits these generated files:
  - `<api>/<api>-openapi.yaml`  (regenerated by scripts/sync_yaml.py)
  - `<api>/<api>-mcp.json`       (regenerated by scripts/make_mcp.py)
  - `<api>/<api>-ptc.json`       (regenerated by scripts/make_ptc.py, seven APIs only)

The PTC surface excludes three APIs (see make_ptc.EXCLUDED). For those the check makes sure
no -ptc.json exists, because a stray file there would put an excluded operation back in
reach of an agent.

All are hand-checked-in but machine-produced, so they can silently drift when a JSON spec
is edited without re-running the generators. This check regenerates each in memory and compares
against the committed file, failing (exit 1) with the exact regen command for any mismatch.
Nothing is written to disk.

Usage: uv run python scripts/check_generated.py [spec.json ...]   (default: all */*-openapi.json)
"""

import pathlib
import sys

from make_mcp import render_mcp
from make_ptc import EXCLUDED, render_ptc
from sync_yaml import render_yaml
import json


def check(json_path: pathlib.Path) -> tuple[list[str], list[str]]:
    """Returns (violations, artifacts checked) — the second is printed on success so a
    reader can see that PTC was covered, or skipped for an excluded API."""
    spec = json.loads(json_path.read_text(encoding="utf-8"))
    violations, checked = [], ["yaml", "mcp"]

    yaml_path = json_path.with_suffix(".yaml")
    expected_yaml = render_yaml(spec)
    if not yaml_path.exists() or yaml_path.read_text(encoding="utf-8") != expected_yaml:
        violations.append(
            f"{yaml_path} is stale — run: uv run python scripts/sync_yaml.py {json_path}"
        )

    mcp_path = pathlib.Path(str(json_path).replace("-openapi.json", "-mcp.json"))
    expected_mcp = render_mcp(spec)
    if not mcp_path.exists() or mcp_path.read_text(encoding="utf-8") != expected_mcp:
        violations.append(
            f"{mcp_path} is stale — run: uv run python scripts/make_mcp.py {json_path}"
        )

    ptc_path = pathlib.Path(str(json_path).replace("-openapi.json", "-ptc.json"))
    if json_path.parent.name in EXCLUDED:
        checked.append("ptc excluded")
        if ptc_path.exists():
            violations.append(
                f"{ptc_path} must not exist — {json_path.parent.name} is excluded from the PTC surface"
            )
    else:
        checked.append("ptc")
        expected_ptc = render_ptc(spec)
        if not ptc_path.exists() or ptc_path.read_text(encoding="utf-8") != expected_ptc:
            violations.append(
                f"{ptc_path} is stale — run: uv run python scripts/make_ptc.py {json_path}"
            )

    return violations, checked


def main() -> int:
    if len(sys.argv) > 1:
        spec_files = [pathlib.Path(a) for a in sys.argv[1:]]
    else:
        spec_files = sorted(pathlib.Path(".").glob("*/*-openapi.json"))

    if not spec_files:
        print("No spec files found.")
        return 1

    all_ok = True
    for path in spec_files:
        violations, checked = check(path)
        if violations:
            all_ok = False
            for v in violations:
                print(f"[FAIL] {v}")
        else:
            print(f"[OK] {path.parent.name} ({', '.join(checked)})")

    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
