"""
Verifies every generated artifact is in sync with its canonical *-openapi.json source.

For each `<api>/<api>-openapi.json` the repo also commits two generated files:
  - `<api>/<api>-openapi.yaml`  (regenerated by scripts/sync_yaml.py)
  - `<api>/<api>-mcp.json`       (regenerated by scripts/make_mcp.py)

Both are hand-checked-in but machine-produced, so they can silently drift when a JSON spec
is edited without re-running the generators. This check regenerates each in memory and compares
against the committed file, failing (exit 1) with the exact regen command for any mismatch.
Nothing is written to disk.

Usage: uv run python scripts/check_generated.py [spec.json ...]   (default: all */*-openapi.json)
"""

import pathlib
import sys

from make_mcp import render_mcp
from sync_yaml import render_yaml
import json


def check(json_path: pathlib.Path) -> list[str]:
    spec = json.loads(json_path.read_text(encoding="utf-8"))
    violations = []

    yaml_path = json_path.with_suffix(".yaml")
    expected_yaml = render_yaml(spec)
    if not yaml_path.exists() or yaml_path.read_text(encoding="utf-8") != expected_yaml:
        violations.append(
            f"{yaml_path} is stale — run: uv run python scripts/sync_yaml.py {json_path}"
        )

    mcp_path = pathlib.Path(str(json_path).replace("-openapi.json", "-mcp.json"))
    expected_mcp = render_mcp(spec)
    if not mcp_path.exists() or mcp_path.read_text(encoding="utf-8") != expected_mcp:
        violations.append(
            f"{mcp_path} is stale — run: uv run python scripts/make_mcp.py {json_path}"
        )

    return violations


def main() -> int:
    if len(sys.argv) > 1:
        spec_files = [pathlib.Path(a) for a in sys.argv[1:]]
    else:
        spec_files = sorted(pathlib.Path(".").glob("*/*-openapi.json"))

    if not spec_files:
        print("No spec files found.")
        return 1

    all_ok = True
    for path in spec_files:
        violations = check(path)
        if violations:
            all_ok = False
            for v in violations:
                print(f"[FAIL] {v}")
        else:
            print(f"[OK] {path.parent.name}")

    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
